### ISSUE TITLE
Duplicate title on website home page

### ISSUE THREAD

**Issue by poppy-townsend** [net-zero-dri/net-zero-dri.github.io#4]
I've tried adding the project title to the home (index.md - https://github.com/net-zero-dri/net-zero-dri.github.io/blob/main/index.md) page in numerous ways. But it keeps duplicating it and I'm not sure why!

**Comment by poppy-townsend** [comment]
https://stackoverflow.com/questions/41070764/github-pages-duplicating-header-from-jekyll - this might help explain it?

**Comment by poppy-townsend** [comment]
I think I've sorted this by editing the title on the config file.

**Comment by agstephens** [comment]
Great work @poppy-townsend !
